//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.01 at 08:59:45 PM EET 
//


package org.bl.algorithm.ws;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.bl.algorithm.ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.bl.algorithm.ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAlgorithmDescribeRequest }
     * 
     */
    public GetAlgorithmDescribeRequest createGetAlgorithmDescribeRequest() {
        return new GetAlgorithmDescribeRequest();
    }

    /**
     * Create an instance of {@link GetAlgorithmWeeklyScheduleRequest }
     * 
     */
    public GetAlgorithmWeeklyScheduleRequest createGetAlgorithmWeeklyScheduleRequest() {
        return new GetAlgorithmWeeklyScheduleRequest();
    }

    /**
     * Create an instance of {@link GetAlgorithmABWithoutIfResponse }
     * 
     */
    public GetAlgorithmABWithoutIfResponse createGetAlgorithmABWithoutIfResponse() {
        return new GetAlgorithmABWithoutIfResponse();
    }

    /**
     * Create an instance of {@link GetAlgorithmABWithoutIfRequest }
     * 
     */
    public GetAlgorithmABWithoutIfRequest createGetAlgorithmABWithoutIfRequest() {
        return new GetAlgorithmABWithoutIfRequest();
    }

    /**
     * Create an instance of {@link GetAlgorithmWeeklyScheduleResponse }
     * 
     */
    public GetAlgorithmWeeklyScheduleResponse createGetAlgorithmWeeklyScheduleResponse() {
        return new GetAlgorithmWeeklyScheduleResponse();
    }

    /**
     * Create an instance of {@link GetAlgorithmDescribeResponse }
     * 
     */
    public GetAlgorithmDescribeResponse createGetAlgorithmDescribeResponse() {
        return new GetAlgorithmDescribeResponse();
    }

    /**
     * Create an instance of {@link Algorithm }
     * 
     */
    public Algorithm createAlgorithm() {
        return new Algorithm();
    }

}
